### PR TITLE
Modified README

### PR DESCRIPTION
**Pull request by fpreciado3**
# Description

- Modified README.md file to have the project's information

### CODE REVIEW

**Review by VISOSO2403 — COMMENTED** [review]
LGTM 😘

**Review by VISOSO2403 — APPROVED** [review]

**Review by Jherrera11 — APPROVED** [review]
LGTM 😘

**Review by Alfredo20164920 — APPROVED** [review]

**Review by FelixAva — APPROVED** [review]
LGTM

**Review by Antonio3veces3 — APPROVED** [review]
Excellent!

**Pull request merged**
