### PR TITLE
Sprint 3/issue 8#company jobs screen view

### LINKED ISSUE #15: sprint-3/issue-8#Company JobsScreen view
## REQUIREMENTS / DESCRIPTION

> Create JobsScreen to the Company view. The screen must have a render of the published jobs
> The job card must have the following data:
 - Brand's logo
 - Branch
 - Job
 - Salary
 - Schedule
 - Button to acces to JobDetails

- The branch, must have a function to cut the text which are longer than 20 caracters

## DESIGN
image

> image

### PR DESCRIPTION
**Pull request by Jherrera11**
# Description

What did you implemented/Why did you implemented this:

-Add new screen
-Add new Images
-Add new data and interface 
-Add new component
-Improve desing in home screen

Examples:

null

## Testing

Null
 Example:

-Null

## Screenshots
image
image

### CODE REVIEW

**Review by VISOSO2403 — CHANGES_REQUESTED** [review]
**Images:**

1. Squoosh the images to reduce their size 
2. use the webp format.

**Components**

1. use rowComponent for buttons
2. if styles are repeated more than once, add them to a file for global styles src/theme/globalTheme.tsx

**Review by Antonio3veces3 — CHANGES_REQUESTED** [review]
Resolve Conflicts!

**Review by Antonio3veces3 — APPROVED** [review]
Well done!

**Review by VISOSO2403 — APPROVED** [review]
Nice job

**Pull request merged**
