### PR TITLE
Fields messages

### LINKED ISSUE #40: sprint-6/issue-19#Sign in and Sign up field's validations.
## REQUIREMENTS / DESCRIPTION

> Password lenght, name structure
> Show the strucutre mistakes on the form, under the field

### PR DESCRIPTION
**Pull request by VISOSO2403**
# Description

- I separated the backend logic that was in the frontend logic.
- I added two components to separate the company and worker forms.
- Install react hook form to place messages in the inputs.

## Screenshots
image

### CODE REVIEW

**Comment by VISOSO2403** [comment]
This is only the first part of my changes, just code refactoring and cleaning up some files.
I'm still working on the react-hook-form implementation.

**Review by Jherrera11 — APPROVED** [review]
Excellent! 
image

**Review by Antonio3veces3 — APPROVED** [review]
Well done!

**Review by FelixAva — APPROVED** [review]
LGTM

**Pull request merged**
