### PR TITLE
4 sprint 2issues 2onboarding screen

### LINKED ISSUE #4: sprint-2/issues-2#OnBoarding Screen
## REQUIREMENTS / DESCRIPTION

>Create an OnBoarding screen, which is an introduction to the purpose of the application in this screen can be navigated through a button.

## DESIGN

image
image
image
image

### PR DESCRIPTION
**Pull request by FelixAva**
# Description

I create the onboarding screen, splitting it on three components.

What did you implemented/Why did you implemented this:

- I create a screen with the name "Onboarding Screen"
- This screen uses two components "Onboarding Body" and "Onboarding Navigation"
- In the "Onboarding Body", the image and text are rendered with their specific styles
- In the "Onboarding Navigation", I created the circles that shows the active page.

Examples:

- What?: I copy the Figma design. I did't use the navigation, because the component which I need to render (Onboarding Body). Onboarding only has two elements (Image and Text) so, I create a object that provides the "page" information

### CODE REVIEW

**Review by VISOSO2403 — CHANGES_REQUESTED** [review]
Make the following changes:
- add an extra line at the end of each modified file, you can set it up in visual code to make it automatic
- Squoosh the images to make them less heavy and change them to webp format.

**Review by fpreciado3 — APPROVED** [review]
LGTM

**Review by Jherrera11 — APPROVED** [review]
LGTM 
images

**Review by VISOSO2403 — APPROVED** [review]
LGTM

**Pull request merged**
