### PR TITLE
46 sprint 6issue 22migration from firebase to supabase

### LINKED ISSUE #46: sprint-6/issue-22#Migration from Firebase to SupaBase
## REQUIREMENTS / DESCRIPTION

> Change the backend technology, use SupaBase.

> Implement:
- Authentication with; email, google and phone
- Real time changes
- CRUD events

### PR DESCRIPTION
**Pull request by FelixAva**
# Description

What did you implemented/Why did you implemented this:

- Migrate to supabase
- Add Authentication
- Add Sign In and Sign Up function
- Add auth listener to move between screens

Examples:

- What?: I've added the authentication to create an account in the app

## Testing

Start the app and fill the fields to sign in/up

 Example:

- I've added coverage for testing all new methods. I used Faker for a few random user emails and names.

### CODE REVIEW

**Review by VISOSO2403 — APPROVED** [review]

**Review by Antonio3veces3 — COMMENTED** [review]
Resolve conflicts before merge

**Review by Jherrera11 — APPROVED** [review]
Approve 👍

**Review by fpreciado3 — APPROVED** [review]
LGTM! 👍😁🙌

**Review by VISOSO2403 — APPROVED** [review]
LGTM

**Review by Alfredo20164920 — APPROVED** [review]

**Pull request merged**
